<?php
   if($_SERVER["HTTP_ACCEPT"] != '*/*') {
         header( 'Location: http://www.meatspin.com' ) ;
    } 
	?>
<?php
$nick = addslashes(htmlentities($_GET['drabbo_naam']));

echo '
simple.memenu.enabled=1
feed.badge_decorations.album=Feed_Badges
image.library.questing.url=https://smurfhotel.nl/r63/c_images/Quests/
productdata.load.url=https://smurfhotel.nl/r63/productdata.txt
logout.url=https://smurfhotel.nl/client
viral.furni.post_type=appRequest
image.library.playlist.url=https://smurfhotel.nl/r63/c_images/playlist/
billboard.adwarning.left.url=AdWarningsUK/ad_warning_L.png
navigator.default.view=public
latencytest.interval=20000
furnidata.load.url=https://smurfhotel.nl/r63/furnidata.txt
external.figurepartlist.txt=https://smurfhotel.nl/r63/figuredata.xml
image.library.url=https://smurfhotel.nl/r63/c_images/
external.texts.txt=https://smurfhotel.nl/r63/external_flash_texts.txt
latencytest.report.delta=100
flash.dynamic.download.name.template=/%typeid%.swf
client.hotel_view.image=hotel_view_images_hq/hotelview_default.png
billboard.adwarning.right.url=AdWarningsUK/ad_warning_R.png
image.library.catalogue.url=https://smurfhotel.nl/r63/c_images/catalogue/
flash.dynamic.download.url=https://smurfhotel.nl/r63/pie/hof_furni/mash/
flash.dynamic.download.samples.template=mp3/sound_machine_sample_%typeid%.mp3
feed.badge_decorations.decoration_id=001
avatareditor.allowclubtryout=1
dynamic.download.name.template=/hh_furni_xx_%typeid%.cct
link.friendbar.stream.settings.see.more=https://smurfhotel.nl/r63/articles/2548-whats-new
private.image.library.url=https://smurfhotel.nl/r63/c_images/
logout.disconnect.url=https://smurfhotel.nl/client
hotelview.banner.url=https://smurfhotel.nl/swfs/banner
latencytest.report.index=3
dynamic.download.samples.template=/%typeid%.cct
dynamic.download.url=https://smurfhotel.nl/r63/pie/hof_furni/mash/
client.allow.facebook.like=1
infostand.use.button.enabled=true
friendbar.stream.enabled=true
catalog.drag_and_drop=true
link.format.friendlist.pref=https://smurfhotel.nl/profile/friendsmanagement?tab=6
club.membership.extend.vip.promotion.enabled=true
group.badge.url=https://smurfhotel.nl/habbo-imaging/badge/%imagerdata%.gif
room.dragging.always_center=0
roomenterad.habblet.enabled=true
questing.showDetailsForNextQuest=false
habboinfotool.url=https://smurfhotel.nl/housekeeping/users/searchParamName=username&database=Stats&searchParamValue=
link.format.credits=https://smurfhotel.nl/credits
friendbar.requests.enabled=true
lagWarningLog.enabled=1
hover.name.enabled=false
client.toolbar.static.enabled=true
questing.useWing=true
questing.startQuestDelayInSeconds=10
client.hotel_view.show_on_startup=1
cfh.usercategories.withnoharasser=101,102,103,104,105,106
catalog.furniture.animation=false
roominfo.widget.enabled=1
navigator.always_open_after_login=0
client.minimail.embed.enabled=true
interstitial.enabled=false
friend_bar.helper.friend_finding.enabled=true
pixels.enabled=true
supersaverads.video.promo.enabled=false
welcome.screen.enabled=0
link.format.club=https://smurfhotel.nl/credits/habboclub
club.subscription.disabled=1
toolbar.new_additions.notification.enabled=true
cfh.usercategories.withharasser=101,102,103,104,105,106
client.fatal.error.url=https://smurfhotel.nl/client_error
embed.showInRoomInfo=true
moderatoractionlog.url=https://theallseeingeye.sulake.com/ase/habbo/us/housekeeping/extra/hobba/moderator_activity.action?searchCriteria.habboName=
groupBadgeInfo.enabled=true
interstitial.interval=120000
purse.widget.currency.shells.enabled=1
interstitial.show.time=5000
roomadmin.url=https://theallseeingeye.sulake.com/ase/habbo/us/housekeeping/extra/hobba/roomadmin_search.action?searchParamType=3&searchParamValue=
client.allow.external.links=1
menu.avatar.enabled=true
client.credits.embed.enabled=true
link.format.mail.compose=https://smurfhotel.nl/r63/me#mail/compose/%recipientid%/%random%/
room.rating.enable=1
navigator.colorlimit.yellow=50
interstitial.max.displays=8
questing.defaultCampaign=room_builder
trax.player.sample.memory.purge.enabled=1
friendbar.notifications.enabled=true
menu.own_avatar.enabled=1
navigator.colorlimit.orange=80
link.format.collectibles=https://smurfhotel.nl/credits/collectibles
link.format.userpage=https://smurfhotel.nl/rd/%ID%
club.membership.extend.basic.promotion.enabled=true
avatar.widget.enabled=1
navigator.default_tab=official
client.logout.enabled=true
infostand.report.show=1
subscription.reminder.when.days.left=5
navigator.colorlimit.red=92
client.news.embed.enabled=false
purse.widget.enabled=1

';
?>